employees_name =str(input(' enter employee name :  '))
print('mr / mrs ' +  employees_name )
number_of_hours_worked_in_a_week =int(input('enter number of hours worked in a week:  '))
print(number_of_hours_worked_in_a_week)
hourly_pay_rate =float(input('hourly pay rate:  '))
print(hourly_pay_rate)
month =str(input('enter the month:  '))
print(month)
federal_tax_withholding_rate =int(input('enter rate for federal tax:  '))
print(federal_tax_withholding_rate)
state_tax_withholding_rate =(input('enter rate fro state tax:  '))
print(state_tax_withholding_rate)
